# Generated by Django 3.2 on 2022-12-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221220_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
