# Generated by Django 3.2 on 2022-12-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='pub_date',
            new_name='year',
        ),
    ]
